Nutrition-App.Operations/Models/Foods/FoodSearchViewModel.cs
using Nutrition_App.Entities;
using System.ComponentModel.DataAnnotations;
namespace Nutrition_App.Operations.Models.Foods
{
    public class FoodSearchViewModel
    {
        [Required(ErrorMessage ="Enter a valid search")]
        public string FoodName { get; set; }
        public List<Food>? QueriedFood {  get; set; }
    }
}

Nutrition-App.Operations/Controllers/FoodsController.cs
using Microsoft.AspNetCore.Mvc;
using Nutrition_App.Data;
using Nutrition_App.Operations.Models;
using Nutrition_App.Operations.Models.Foods;
using Nutrition_App.Services;

namespace Nutrition_App.Operations.Controllers
{
    public class FoodsController : Controller
    {
        private IFoodServices _foodServices;

        public FoodsController(IFoodServices foodServices)
        {
            _foodServices = foodServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Search()
        {
            return View(new FoodSearchViewModel());
        }

        [HttpPost]
        public IActionResult Search(FoodSearchViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.QueriedFood = _foodServices.GetFoodsByString(model.FoodName);
            }
            return View(model);
        }
    }
}

Nutrition-App.Operations/Controllers/LogController.cs
using Microsoft.AspNetCore.Mvc;
using Nutrition_App.Services;
using Nutrition_App.Entities;
using Nutrition_App.Operations.Models.Log;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Nutrition_App.Operations.Models.Nutrients;

namespace Nutrition_App.Operations.Controllers
{
    [Authorize]
    public class LogController : Controller
    {
        private IFoodServices _foodServices;
        private IUserServices _userServices;
        private IDietLogServices _dietLogServices;

        public LogController(IFoodServices foodServices, IUserServices userServices, IDietLogServices dietLogServices)
        {
            _foodServices = foodServices;
            _userServices = userServices;
            _dietLogServices = dietLogServices;
        }

        public IActionResult AddFoodToLog(int id)
        {
            AddFoodToLogViewModel model = new AddFoodToLogViewModel();

            Food food = _foodServices.GetFoodById(id);

            model.FoodId = id;
            model.Food = food;
            model.Description = food.Description;
            model.DateEaten = DateTime.Now;

            return View(model);
        }
        [HttpPost]
        public IActionResult AddFoodToLog(AddFoodToLogViewModel model)
        {
            model.Food = _foodServices.GetFoodById(model.FoodId);
            if (model.Food == null) return View(model);

            DietLog dietLog = new DietLog
            {
                FoodId = model.FoodId,
                UserId = _userServices.GetUserByUsername(User.Identity.Name).Result.Id,
                DateEaten = model.DateEaten,
                WeightEaten = model.WeightEaten
            };

            _dietLogServices.CreateDietLog(dietLog);

            return RedirectToAction("View");
        }

        [Authorize]
        [HttpGet]
        public IActionResult View()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var dietLogs = _dietLogServices.GetDietLogsByUser(userId);
            var foods = _foodServices.GetFoodsByDietLogs(dietLogs);
            var foodMap = foods.ToDictionary(f => f.Id, f => f); // faster than searching through foods table for every diet log

            var rows = dietLogs.Select(l => new DietLogRow
            {
                DietLog = l,
                Food = foodMap[l.FoodId]
            }).ToList();

            var model = new ViewDietLogViewModel
            {
                Rows = rows
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            EditLogViewModel model = new EditLogViewModel();

            DietLog dietLog = _dietLogServices.GetDietLog(id);
            Food food = _foodServices.GetFoodById(dietLog.FoodId);
            model.FoodId = food.Id;
            model.Food = food;
            model.Description = food.Description;
            model.DateEaten = DateTime.Now;
            model.WeightEaten = dietLog.WeightEaten;
            model.DietLogId = id;

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditLogViewModel model)
        {
            model.Food = _foodServices.GetFoodById(model.FoodId);

            DietLog existing = _dietLogServices.GetDietLog(model.DietLogId);
            existing.WeightEaten = model.WeightEaten;
            existing.DateEaten = model.DateEaten;
            _dietLogServices.UpdateDietLog(existing);

            return RedirectToAction("View");
        }

        public IActionResult Delete(int id)
        {

            _dietLogServices.DeleteDietLog(id);
            return RedirectToAction("View");
        }
    }
}

Nutrition-App.Operations/Controllers/NutrientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nutrition_App.Data;
using Nutrition_App.Operations.Models.Nutrients;
using Nutrition_App.Services;

namespace Nutrition_App.Operations.Controllers
{
    public class NutrientsController : Controller
    {
        private readonly IFoodServices _foodServices;
        public NutrientsController(IFoodServices foodServices)
        {
            _foodServices = foodServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult View(int id)
        {
            var food = _foodServices.GetFoodById(id);

            var model = new NutrientViewModel
            {
                Food = food,
                FoodId = id,
                FoodDescription = food.Description,
                WeightEaten = 100
            };

            return View(model);
        }

        [HttpPost]
        [ActionName("View")]
        public IActionResult ViewPost(NutrientViewModel model)
        { 
            model.Food = _foodServices.GetFoodById(model.FoodId);

            return View(model);
        }

        [HttpGet]
        public IActionResult ViewDietLog(string foodId, string weightEaten)
        {
            double parsedWeight = 0;
            try
            {
                parsedWeight = Double.Parse(weightEaten);
            }
            catch (Exception ex) {}

            var model = new ViewDietLogViewModel
            {
                WeightEaten = parsedWeight,
                Food = _foodServices.GetFoodById(int.Parse(foodId))
            };

            return View(model);
        }
    }
}

Nutrition-App.Operations/Views/Foods/Search.cshtml
@model Nutrition_App.Operations.Models.Foods.FoodSearchViewModel

<h1>Search Foods</h1>
<br />

<p>Sample query (exact): Pork, chop, lean and fat eaten</p>
<p>Sample query (general): Cheese</p>
<br />

<form asp-action="Search" method="post" class="mb-3">
    <div class="form-group">
        <label asp-for="FoodName">Food description:</label>
        <input type="text" asp-for="FoodName" class="form-control" />
        <span asp-validation-for="FoodName" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Search</button>
</form>

@if (Model.QueriedFood != null)
{
    <br />
    <h2>Search Results: @Model.QueriedFood.Count</h2>
    <br />

    <table class="table table-striped table-hover table-bordered">
        <thead class="table-dark">
            <tr>
                <th>Description</th>
                <th style="min-width: 250px">Action</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.QueriedFood.Count; i++)
            {
                <tr>
                    <td>@Model.QueriedFood[i].Description</td>
                    <td>
                        <a asp-controller="Nutrients"
                           asp-action="View"
                           asp-route-id="@Model.QueriedFood[i].Id">
                            View Nutrients
                        </a>
                          |  
                        <a asp-controller="Log"
                           asp-action="AddFoodToLog"
                            asp-route-id="@Model.QueriedFood[i].Id">
                            Add to Log
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}